services:
  web:
    container_name: portfolio-adrien
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./PORTFOLIO-ADRIEN:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
    external: true
    name: webnet
